name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  ci:
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Add MSVC to PATH
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        run: CALL "build.bat"
        shell: cmd

      - name: Prepare files
        run: |
          mkdir dist
          cp CPP/7zip/Bundles/Alone/x64/7za.exe dist/
        shell: bash

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: "7za_x64_MSVC2022"
          path: dist/
          if-no-files-found: error
